### ISSUE TITLE
Error: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by antonioribeiro** [luislavena/greek-steam#3]
I'm having this error when trying to pull on Docker:

```
docker pull ghcr.io/luislavena/greek-steam:8.2.25
```

Got this first when trying to deploy a Laravel Vapor app from my local:

```

==> Building Container Image
Build command: docker build --pull --file=internal.Dockerfile --tag=client-website:internal --build-arg='__VAPOR_RUNTIME=docker' .
#0 building with "desktop-linux" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from internal.Dockerfile
#2 transferring dockerfile: 104B done
#2 DONE 0.0s

#3 [internal] load metadata for ghcr.io/luislavena/greek-steam:8.1
#3 ERROR: no match for platform in manifest sha256:0ee93204daafcafacaf39ceee519bb96e3ccac119ae56b749af033b748158112: not found
------
 > [internal] load metadata for ghcr.io/luislavena/greek-steam:8.1:
------
internal.Dockerfile:1
--------------------
   1 | >>> FROM ghcr.io/luislavena/greek-steam:8.1
   2 |
   3 |     COPY . /var/task
--------------------
ERROR: failed to solve: ghcr.io/luislavena/greek-steam:8.1: no match for platform in manifest sha256:0ee93204daafcafacaf39ceee519bb96e3ccac119ae56b749af033b748158112: not found

In Process.php line 270:

  The command "docker build --pull --file=internal.Dockerfile --tag=client-website:internal --build-arg='__VAPOR_RUNTIME=docker' ." failed.

  Exit Code: 1(General error)

  Working directory: ~/client/client-website/.vapor/build/app

  Output:
  ================


  Error Output:
  ================
  #0 building with "desktop-linux" instance using docker driver

  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s

  #2 [internal] load build definition from internal.Dockerfile
  #2 transferring dockerfile: 104B done
  #2 DONE 0.0s

  #3 [internal] load metadata for ghcr.io/luislavena/greek-steam:8.1
  #3 ERROR: no match for platform in manifest sha256:0ee93204daafcafacaf39ceee519bb96e3ccac119ae56b749af033b748158112: not found
  ------
   > [internal] load metadata for ghcr.io/luislavena/greek-steam:8.1:
  ------
  internal.Dockerfile:1
  --------------------
     1 | >>> FROM ghcr.io/luislavena/greek-steam:8.1
     2 |
     3 |     COPY . /var/task
  --------------------
  ERROR: failed to solve: ghcr.io/luislavena/greek-steam:8.1: no match for platform in manifest sha256:0ee93204daafcafacaf39ceee519bb96e3ccac119ae56b749af033b748158112: not found
```

**Comment by luislavena** [comment]
Hello @antonioribeiro, the existing container images do not support arm64 platform (`linux/arm64`).

It should be simple to add linux/arm64 support to the same image, following what I've done with hydrofoil-php. That is, of course, if you're building on arm64 and deploying to arm64 containers.

However, If you're using an Apple Silicon machine to build and then deploy to amd64, it could be the issue. There are some notes on [Vapor](https://blog.laravel.com/vapor-arm-support) own blog, but the example uses a specific tag for the architecture. Their docs are a bit [vague](https://docs.vapor.build/projects/environments.html#runtime) about it too, so not precisely sure how to trigger the build of amd64 instead of arm64.

Let me know if that somehow helps.

Cheers.

**Comment by antonioribeiro** [comment]
@luislavena, I'm using an Apple Silicon, and your clues helped, yes! As we are currently using `runtime: docker` switching to `runtime: docker-arm` and also moving to `hydrofoil`: `FROM ghcr.io/luislavena/hydrofoil-php:8.1` fixed it. 

If you could add linux/arm64 support to `greek-steam`, it would be great. 

Thank you!

**Comment by luislavena** [comment]
@antonioribeiro please note that hydrofoil-php is not meant for production usage as is using the dev mode PHP configuration.

I keep this open until I push a multi arch container image.

Cheers,

**Comment by antonioribeiro** [comment]
I know, @luislavena , it was just to test if it would work. 

Cheers!
